#!/usr/bin/env python
#
# poek_writer [-d] <filename> <model> [<data> ...]
#

import sys
import os.path

sys.path.insert(1, os.path.dirname(os.path.abspath(__file__)) )
from models import create_instance, print_help

if len(sys.argv) == 1:
    print("poek_writer [-d] <filename> <model> [<data> ...]")
    print_help()
    sys.exit(1)

i=1
if sys.argv[i] == '-d':
    debug=True
    i += 1
else:
    debug=False
filename = sys.argv[i]
i += 1
model = sys.argv[i]
i += 1
data = [int(val) for val in sys.argv[i:]]

instance = create_instance(model, data)
if not instance
    print("Unknown poek model '%s'" % solver)
    sys.exit(1)

if debug:
    print("Writing file:",filename)
instance.write(filename)
