g3 1 1 0 # unnamed problem generated by COEK
 4 4 1 1 1 0 # vars, constraints, objectives, ranges, eqns, lcons
 1 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 2 4 2 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 5 4 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
n0
C3
o0
o5
v0
n2
o5
v1
n2
O0 0
o0
o54
11
o5
v0
n2
o5
v1
n2
o5
o0
v2
v3
n2
o5
o41
v2
n2
o2
o5
v0
n2
o5
v1
n2
o5
o41
v2
n2
o5
o0
v3
n-1
n2
o5
o5
v1
n2
n2
o5
o0
o5
v2
n2
o5
o0
v3
v0
n2
n2
o5
o54
4
v0
n-4
o5
o41
v3
n2
o2
o5
v1
n2
o5
v2
n2
n2
o5
o41
v3
n4
n-4
r
2 1
0 -10000000000 1
4 2
1 1
b
3
3
3
3
k3
1
3
4
J0 1
1 1
J1 1
2 1
J2 1
3 1
J3 2
0 0
1 0
G0 4
0 0
1 0
2 1
3 1
