g3 1 1 0 # unnamed problem generated by COEK
 2 2 1 0 2 0 # vars, constraints, objectives, ranges, eqns, lcons
 0 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 0 0 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 4 0 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
O0 0
n0
r
4 7
4 5
b
3
3
k1
2
J0 2
0 1
1 2
J1 2
0 2
1 1
