g3 1 1 0 # unnamed problem generated by COEK
 6 4 1 0 0 0 # vars, constraints, objectives, ranges, eqns, lcons
 4 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 5 0 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 20 6 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o54
5
o2
n-169
o2
v0
v2
o2
n-3580
o2
v2
v4
o2
n-3810
o2
v3
v4
o2
n-18500
o2
v3
v5
o2
n-24300
o2
v4
v5
C1
o54
4
o2
n-139
o2
v0
v2
o2
n-2450
o2
v3
v4
o2
n-16600
o2
v3
v5
o2
n-17200
o2
v4
v5
C2
o2
n26000
o2
v3
v4
C3
o2
n-14000
o2
v0
v5
O0 0
n0
x6
0 0
1 0
2 0
3 0
4 0
5 0
r
2 4.97
2 -1.88
2 -29.08
2 -78.02
b
0 0 0.31
0 0 0.046
0 0 0.068
0 0 0.042
0 0 0.028
0 0 0.0134
k5
3
7
9
13
17
J0 6
0 17.1
1 38.2
2 204.2
3 212.3
4 623.4
5 1495.5
J1 6
0 17.9
1 36.8
2 113.9
3 169.7
4 337.8
5 1385.2
J2 3
1 -273
3 -70
4 -819
J3 5
0 159.9
1 -311
3 587
4 391
5 2198
G0 6
0 4.3
1 31.8
2 63.3
3 15.8
4 68.5
5 4.7
