g3 1 1 0 # unnamed problem generated by COEK
 9 10 1 0 6 0 # vars, constraints, objectives, ranges, eqns, lcons
 8 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 9 2 2 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 42 2 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
o0
o2
n-1
o5
v0
n2
o2
n-1
o5
v7
n2
C3
o0
o2
n-1
o5
v1
n2
o2
n-1
o5
v8
n2
C4
o54
3
o2
o2
v4
v5
o41
o0
o2
n-1
v2
n-0.25
o2
o2
v4
v6
o41
o0
o2
n-1
v3
n-0.25
o2
n0.4948079185090459
o5
v4
n2
C5
o54
3
o2
o2
v4
v5
o41
o0
v2
n-0.25
o2
o2
v5
v6
o41
o54
3
v2
o2
n-1
v3
n-0.25
o2
n0.4948079185090459
o5
v5
n2
C6
o54
3
o2
o2
v4
v6
o41
o0
v3
n-0.25
o2
o2
v5
v6
o41
o54
3
v3
o2
n-1
v2
n-0.25
o2
n0.4948079185090459
o5
v6
n2
C7
o54
4
o2
o2
v4
v5
o46
o0
o2
n-1
v2
n-0.25
o2
o2
v4
v6
o46
o0
o2
n-1
v3
n-0.25
o2
n-1.937824843421289
o5
v4
n2
o2
n0.0377975808
o5
v4
n2
C8
o54
4
o2
o2
v4
v5
o46
o0
v2
n-0.25
o2
o2
v5
v6
o46
o54
3
v2
o2
n-1
v3
n-0.25
o2
n-1.937824843421289
o5
v5
n2
o2
n0.0377975808
o5
v5
n2
C9
o54
4
o2
o2
v4
v6
o46
o0
v3
n-0.25
o2
o2
v5
v6
o46
o54
3
v3
o2
n-1
v2
n-0.25
o2
n-1.937824843421289
o5
v6
n2
o2
n0.0377975808
o5
v6
n2
O0 0
o0
o2
n1e-06
o5
v0
n3
o2
n5.22074e-07
o5
v1
n3
x9
0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
r
2 -0.55
2 -0.55
2 -2250000
2 -2250000
4 -20070.4
4 -20070.4
4 -44244.143104
4 10035.2
4 10035.2
4 -1150.937088
b
2 0
2 0
0 -0.55 0.55
0 -0.55 0.55
0 196 252
0 196 252
0 196 252
0 -400 800
0 -400 800
k8
2
4
12
20
26
32
38
40
J0 2
2 -1
3 1
J1 2
2 1
3 -1
J2 2
0 0
7 0
J3 2
1 0
8 0
J4 6
0 -50.176
2 0
3 0
4 0
5 0
6 0
J5 6
1 -50.176
2 0
3 0
4 0
5 0
6 0
J6 5
2 0
3 0
4 0
5 0
6 0
J7 6
2 0
3 0
4 0
5 0
6 0
7 50.176
J8 6
2 0
3 0
4 0
5 0
6 0
8 50.176
J9 5
2 0
3 0
4 0
5 0
6 0
G0 2
0 3
1 2
