g3 1 1 0 # unnamed problem generated by COEK
 7 2 1 0 2 0 # vars, constraints, objectives, ranges, eqns, lcons
 2 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 4 7 4 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 10 7 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o54
3
o2
n2
o5
v0
n2
o2
n3
o5
v1
n4
o2
n4
o5
v3
n2
C1
o0
o2
n3
o2
v0
v1
o54
3
o2
n-4
o5
v0
n2
o2
n-1
o5
v1
n2
o2
n-2
o5
v2
n2
O0 0
o0
o2
n-4
o2
v5
v6
o54
7
o5
o0
v0
n-10
n2
o2
n5
o5
o0
v1
n-12
n2
o5
v2
n4
o2
n3
o5
o0
v3
n-11
n2
o2
n10
o5
v4
n6
o2
n7
o5
v5
n2
o5
v6
n4
x7
0 1
1 2
2 0
3 4
4 0
5 1
6 1
r
4 127
4 0
b
3
3
3
3
3
3
3
k6
2
4
6
7
8
9
J0 5
0 0
1 0
2 1
3 0
4 5
J1 5
0 0
1 0
2 0
5 -5
6 11
G0 7
0 0
1 0
2 0
3 0
4 0
5 -10
6 -8
