g3 1 1 0 # unnamed problem generated by COEK
 10 11 1 0 3 0 # vars, constraints, objectives, ranges, eqns, lcons
 6 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 7 2 1 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 31 6 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
n0
C3
n0
C4
o0
o2
n0.13167
o2
v0
v7
o2
o2
n0.00667
v0
o5
v7
n2
C5
o2
n-0.038
o5
v7
n2
C6
o0
o2
n-0.13167
o2
v0
v7
o2
o2
n0.00667
v0
o5
v7
n2
C7
o2
n0.038
o5
v7
n2
C8
n0
C9
o3
o2
n98000
v2
o0
o2
v3
v8
o2
n1000
v2
C10
o3
o0
v1
v4
v0
O0 0
o2
n-0.063
o2
v3
v6
x10
0 1745
1 12000
2 110
3 3048
4 1974
5 89.2
6 92.8
7 8
8 3.6
9 145
r
2 -35.82
2 133
2 35.82
2 -133
2 0
2 -57.425
2 0
2 57.425
4 0
4 0
4 0
b
0 1e-05 2000
0 1e-05 16000
0 1e-05 120
0 1e-05 5000
0 1e-05 2000
0 85 93
0 90 95
0 3 12
0 1.2 4
0 145 162
k9
4
5
6
10
12
15
19
24
27
J0 2
8 -0.9
9 -0.222
J1 2
6 3
9 -0.99
J2 2
8 1.111111111111111
9 0.222
J3 2
6 -3
9 1.01010101010101
J4 3
0 1.12
3 -0.99
7 0
J5 3
5 0.325
6 -0.99
7 1.098
J6 3
0 -1.12
3 1.01010101010101
7 0
J7 3
5 -0.325
6 1.01010101010101
7 -1.098
J8 3
0 -1
3 1.22
4 -1
J9 4
2 0
3 0
5 -1
8 0
J10 4
0 0
1 0
4 0
7 -1
G0 6
0 5.04
1 0.035
2 10
3 0
4 3.36
6 0
