g3 1 1 0 # unnamed problem generated by COEK
 4 6 1 1 3 0 # vars, constraints, objectives, ranges, eqns, lcons
 3 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 2 0 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 1 1 0 2 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 11 1 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
o0
o2
n3
o2
v0
v1
o2
n2
o2
v1
v1
C3
o54
3
o2
n-1
o2
v0
v0
o2
n-1
o2
v0
v1
o2
n3
o2
v1
v1
C4
o54
3
o2
n-1
o2
v0
v0
o2
n-1
o2
v0
v1
o2
n3
o2
v1
v1
C5
n0
O0 0
n2
x2
0 0
1 0
r
1 -2
4 0
4 -2
1 -2
0 -9 5
4 0
b
0 0 1
0 0 1
2 0
1 0
k3
4
9
10
J0 2
0 -1
1 3
J1 1
1 4
J2 2
0 0
1 0
J3 2
0 0
1 0
J4 2
0 0
1 0
J5 2
2 1
3 1
G0 1
0 3
