g3 1 1 0 # unnamed problem generated by COEK
 1 0 1 0 0 0 # vars, constraints, objectives, ranges, eqns, lcons
 0 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 0 1 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 1 0 0 1 # discrete variables: binary, integer, nonlinear (b,c,o)
 0 1 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
O0 0
o0
o0
o2
o2
o2
v0
v0
v0
o54
4
o2
n-1
v0
n2
o2
n3
v0
o2
n3
n2
o41
o16
o46
v0
n2
x1
0 0
b
0 0 1
k0
G0 1
0 3
