g3 1 1 0 # unnamed problem generated by COEK
 1 0 1 0 0 0 # vars, constraints, objectives, ranges, eqns, lcons
 0 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 0 0 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 0 1 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
O0 0
n0
x1
0 0
b
4 2
k0
G0 1
0 1
