g3 1 1 0 # unnamed problem generated by COEK
 2 6 1 0 6 0 # vars, constraints, objectives, ranges, eqns, lcons
 4 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 2 2 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 11 1 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o2
v0
v1
C1
o2
n0
o2
v0
v1
C2
n0
C3
o2
v0
v1
C4
o2
n0
o2
v0
v1
C5
n0
O0 0
n0
x0
r
4 1
4 1
4 1
4 1
4 1
4 1
b
3
3
k1
5
J0 2
0 1
1 0
J1 2
0 1
1 0
J2 2
0 1
1 0
J3 2
0 0
1 0
J4 2
0 0
1 0
J5 1
1 0
G0 1
0 1
