g3 1 1 0 # unnamed problem generated by COEK
 3 24 1 0 24 0 # vars, constraints, objectives, ranges, eqns, lcons
 24 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 3 3 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 72 1 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C1
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C2
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C3
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C4
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C5
o0
o2
v0
v2
o2
n-1
o2
v1
v2
C6
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C7
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C8
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C9
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C10
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C11
o0
o2
v0
v2
o2
n-1
o2
v1
v2
C12
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C13
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C14
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C15
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C16
o0
o2
n0.25
o2
v0
v2
o2
n-0.25
o2
v1
v2
C17
o0
o2
v0
v2
o2
n-1
o2
v1
v2
C18
o0
o2
n0.0625
o2
v0
v2
o2
n-0.0625
o2
v1
v2
C19
o0
o2
n0.0625
o2
v0
v2
o2
n-0.0625
o2
v1
v2
C20
o0
o2
n0.0625
o2
v0
v2
o2
n-0.0625
o2
v1
v2
C21
o0
o2
n0.25
o2
v0
v2
o2
n-0.0625
o2
v1
v2
C22
o0
o2
n0.0625
o2
v0
v2
o2
n-0.0625
o2
v1
v2
C23
o0
o2
v0
v2
o2
n-1
o2
v1
v2
O0 0
n0
x3
0 1
1 2
2 3
r
4 2
4 2
4 2
4 2
4 2
4 8
4 2
4 2
4 2
4 2
4 2
4 8
4 2
4 2
4 2
4 2
4 2
4 8
4 2
4 2
4 2
4 2
4 2
4 -16
b
0 -1 1
0 -1 1
0 -1 1
k2
24
48
J0 3
0 0
1 0
2 0
J1 3
0 0
1 0
2 0
J2 3
0 0
1 0
2 0
J3 3
0 0
1 0
2 0
J4 3
0 0
1 0
2 0
J5 3
0 0
1 0
2 0
J6 3
0 0
1 0
2 0
J7 3
0 0
1 0
2 0
J8 3
0 0
1 0
2 0
J9 3
0 0
1 0
2 0
J10 3
0 0
1 0
2 0
J11 3
0 0
1 0
2 0
J12 3
0 0
1 0
2 0
J13 3
0 0
1 0
2 0
J14 3
0 0
1 0
2 0
J15 3
0 0
1 0
2 0
J16 3
0 0
1 0
2 0
J17 3
0 0
1 0
2 0
J18 3
0 0
1 0
2 0
J19 3
0 0
1 0
2 0
J20 3
0 0
1 0
2 0
J21 3
0 0
1 0
2 0
J22 3
0 0
1 0
2 0
J23 3
0 0
1 0
2 0
G0 1
0 1
