g3 1 1 0 # unnamed problem generated by COEK
 7 24 1 0 24 0 # vars, constraints, objectives, ranges, eqns, lcons
 22 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 7 3 3 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 73 3 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
o35
o23
v3
n0
v0
v1
C3
o35
o23
v2
n0
v0
v1
C4
o35
o23
v4
n0
v0
v1
C5
o35
o22
v3
n0
v0
v1
C6
o35
o22
v2
n0
v0
v1
C7
o35
o22
v4
n0
v0
v1
C8
o35
o23
n0
o2
n10
v3
v0
v1
C9
o35
o23
n0
o2
n10
v2
v0
v1
C10
o35
o23
n0
o2
n10
v4
v0
v1
C11
o35
o22
n0
o2
n10
v3
v0
v1
C12
o35
o22
n0
o2
n10
v2
v0
v1
C13
o35
o22
n0
o2
n10
v4
v0
v1
C14
o35
o21
o23
n-1
v5
o23
v5
n1
v0
v1
C15
o35
o21
o23
o2
n-1
v4
v3
o23
v3
n1
v0
v1
C16
o35
o21
o23
o2
o2
n-1
v4
v4
v2
o23
v2
n1
v0
v1
C17
o35
o21
o23
v3
v4
o23
v4
n1
v0
v1
C18
o35
o21
o23
n-1
v6
o23
v6
n1
v0
v1
C19
o35
o21
o22
n-1
v5
o22
v5
n1
v0
v1
C20
o35
o21
o22
n-1
v3
o22
v3
v4
v0
v1
C21
o35
o21
o22
n-1
v2
o22
v2
o2
v4
v4
v0
v1
C22
o35
o21
o22
n-1
v4
o22
v4
v4
v0
v1
C23
o35
o21
o22
n-1
v6
o22
v6
n1
v0
v1
O0 0
o2
n10
o35
v2
v0
v1
x7
0 1
1 -1
2 -1
3 1
4 0
5 -2
6 2
r
4 -1
4 1
4 1
4 1
4 -1
4 1
4 -1
4 -1
4 -1
4 1
4 1
4 -1
4 -1
4 1
4 -1
4 1
4 1
4 1
4 -1
4 -1
4 -1
4 1
4 -1
4 -1
b
3
3
3
3
3
3
3
k6
23
46
52
59
69
71
J0 1
1 1
J1 1
0 1
J2 3
0 0
1 0
3 0
J3 3
0 0
1 0
2 0
J4 3
0 0
1 0
4 0
J5 3
0 0
1 0
3 0
J6 3
0 0
1 0
2 0
J7 3
0 0
1 0
4 0
J8 3
0 0
1 0
3 0
J9 3
0 0
1 0
2 0
J10 3
0 0
1 0
4 0
J11 3
0 0
1 0
3 0
J12 3
0 0
1 0
2 0
J13 3
0 0
1 0
4 0
J14 3
0 0
1 0
5 0
J15 4
0 0
1 0
3 0
4 0
J16 4
0 0
1 0
2 0
4 0
J17 4
0 0
1 0
3 0
4 0
J18 3
0 0
1 0
6 0
J19 3
0 0
1 0
5 0
J20 4
0 0
1 0
3 0
4 0
J21 4
0 0
1 0
2 0
4 0
J22 3
0 0
1 0
4 0
J23 3
0 0
1 0
6 0
G0 3
0 0
1 0
2 0
