g3 1 1 0 # unnamed problem generated by COEK
 3 6 1 0 6 0 # vars, constraints, objectives, ranges, eqns, lcons
 6 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 3 0 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 18 1 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o0
o2
n0.5
o2
v0
v2
o2
n-0.5
o2
v1
v2
C1
o0
o2
n0.5
o2
v0
v2
o2
n-0.5
o2
v1
v2
C2
o0
o2
n0.5
o2
v0
v2
o2
n-0.5
o2
v1
v2
C3
o0
o2
n0.5
o2
v0
v2
o2
n-0.5
o2
v1
v2
C4
o0
o2
n0.5
o2
v0
v2
o2
n-0.5
o2
v1
v2
C5
o0
o2
v0
v2
o2
n-1
o2
v1
v2
O0 0
n0
x3
0 1
1 2
2 3
r
4 2
4 2
4 2
4 2
4 2
4 4
b
0 -1 1
0 -1 1
0 -1 1
k2
6
12
J0 3
0 0
1 0
2 0
J1 3
0 0
1 0
2 0
J2 3
0 0
1 0
2 0
J3 3
0 0
1 0
2 0
J4 3
0 0
1 0
2 0
J5 3
0 0
1 0
2 0
G0 1
0 1
