g3 1 1 0 # unnamed problem generated by COEK
 5 1 1 0 1 0 # vars, constraints, objectives, ranges, eqns, lcons
 1 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 2 3 1 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 1 1 1 1 2 # discrete variables: binary, integer, nonlinear (b,c,o)
 3 3 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o0
o46
v0
o46
v1
O0 0
o0
o46
v2
o46
v0
x5
0 0
1 0
2 0
3 0
4 0
r
4 1
b
0 0 1
0 0 1
0 0 1
0 0 1
0 0 1
k4
1
2
2
3
J0 3
0 0
1 0
3 1
G0 3
0 0
2 0
4 1
