#pragma once

namespace coek {

enum term_id : unsigned int {
    ConstantTerm_id = 1,
    ParameterTerm_id = 2,
    VariableTerm_id = 3,
    VariableRefTerm_id = 4,
    MonomialTerm_id = 5,
    InequalityTerm_id = 6,
    EqualityTerm_id = 7,
    NegateTerm_id = 8,
    PlusTerm_id = 9,
    TimesTerm_id = 10,
    DivideTerm_id = 11,
    AbsTerm_id = 12,
    CeilTerm_id = 13,
    FloorTerm_id = 14,
    ExpTerm_id = 15,
    LogTerm_id = 16,
    Log10Term_id = 17,
    SqrtTerm_id = 18,
    SinTerm_id = 19,
    CosTerm_id = 20,
    TanTerm_id = 21,
    SinhTerm_id = 22,
    CoshTerm_id = 23,
    TanhTerm_id = 24,
    ASinTerm_id = 25,
    ACosTerm_id = 26,
    ATanTerm_id = 27,
    ASinhTerm_id = 28,
    ACoshTerm_id = 29,
    ATanhTerm_id = 30,
    PowTerm_id = 31,
    IndexParameterTerm_id = 100,
    // IndexedVariableTerm_id = 101,
    SumExpressionTerm_id = 102,
    ObjectiveTerm_id = 103,
    EmptyConstraintTerm_id = 104,
    // EmptyObjectiveTerm_id = 105,
    ParameterRefTerm_id = 106,
    SubExpressionTerm_id = 107,
    IfThenElseTerm_id = 108,
    DefinedValueTerm_id = 109,
    StrictInequalityTerm_id = 110,
    DataRefTerm_id = 111,
};

}  // namespace coek
