g3 1 1 0 # unnamed problem generated by COEK
 5 2 1 0 2 0 # vars, constraints, objectives, ranges, eqns, lcons
 2 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 5 5 5 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 5 5 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o0
o2
v3
o5
v0
n2
o41
o0
v3
o2
n-1
v4
C1
o2
o5
v2
n4
o5
v1
n2
O0 0
o54
5
o5
o0
v0
n-1
n2
o5
o0
v0
o2
n-1
v1
n2
o5
o0
v2
n-1
n2
o5
o0
v3
n-1
n4
o5
o0
v4
n-1
n6
x5
0 2
1 2
2 2
3 2
4 2
r
4 2.82842712474619
4 9.414213562373096
b
3
3
3
3
3
k4
1
2
3
4
J0 3
0 0
3 0
4 0
J1 2
1 1
2 0
G0 5
0 0
1 0
2 0
3 0
4 0
