g3 1 1 0 # unnamed problem generated by COEK
 9 9 1 0 9 0 # vars, constraints, objectives, ranges, eqns, lcons
 3 0 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 9 0 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 45 0 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
n0
C3
o54
9
o2
n1.3725e-07
o2
v0
v0
o2
n937.62
o2
v0
v3
o2
n-42.207
o2
v0
v6
o2
n1.3725e-07
o2
v1
v3
o2
n1.3725e-07
o2
v2
v6
o2
n937.62
o2
v3
v4
o2
n-42.207
o2
v3
v7
o2
n937.62
o2
v5
v6
o2
n-42.207
o2
v6
v8
C4
o54
9
o2
n1.3725e-07
o2
v0
v1
o2
n937.62
o2
v1
v3
o2
n1.3725e-07
o2
v1
v4
o2
n-42.207
o2
v1
v6
o2
n1.3725e-07
o2
v2
v7
o2
n937.62
o2
v4
v4
o2
n-42.207
o2
v4
v7
o2
n937.62
o2
v5
v7
o2
n-42.207
o2
v7
v8
C5
o54
9
o2
n1.3725e-07
o2
v0
v2
o2
n1.3725e-07
o2
v1
v5
o2
n937.62
o2
v2
v3
o2
n-42.207
o2
v2
v6
o2
n1.3725e-07
o2
v2
v8
o2
n937.62
o2
v4
v5
o2
n-42.207
o2
v5
v7
o2
n937.62
o2
v5
v8
o2
n-42.207
o2
v8
v8
C6
n0
C7
n0
C8
n0
O0 0
n0
x9
0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
r
4 0
4 -44.792
4 0
4 0
4 -948.21
4 0
4 0
4 42.684
4 0
b
3
3
3
3
3
3
3
3
3
k8
5
10
15
20
25
30
35
40
J0 3
0 0.0060893
3 -44.292
6 2.0011
J1 3
1 0.0060893
4 -44.292
7 2.0011
J2 3
2 0.0060893
5 -44.292
8 2.0011
J3 9
0 1.388e-07
1 0
2 0
3 -1886
4 0
5 0
6 42.362
7 0
8 0
J4 9
0 0
1 1.388e-07
2 0
3 0
4 -1886
5 0
6 0
7 42.362
8 0
J5 9
0 0
1 0
2 1.388e-07
3 0
4 0
5 -1886
6 0
7 0
8 42.362
J6 3
0 -1.3877e-07
3 42.362
6 -2.0705
J7 3
1 -1.3877e-07
4 42.362
7 -2.0705
J8 3
2 -1.3877e-07
5 42.362
8 -2.0705
