g3 1 1 0 # unnamed problem generated by COEK
 10 5 1 0 5 0 # vars, constraints, objectives, ranges, eqns, lcons
 5 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 10 10 10 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 30 10 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o2
v0
v1
C1
o2
o2
o2
v0
v1
v2
v3
C2
o2
o2
o2
o2
o2
v0
v1
v2
v3
v4
v5
C3
o2
o2
o2
o2
o2
o2
o2
v0
v1
v2
v3
v4
v5
v6
v7
C4
o2
o2
o2
o2
o2
o2
o2
o2
o2
v0
v1
v2
v3
v4
v5
v6
v7
v8
v9
O0 0
o54
9
o2
n19.8
o2
v1
v3
o2
n19.8
o2
v2
v4
o2
n19.8
o2
v3
v5
o2
n19.8
o2
v4
v6
o2
n19.8
o2
v5
v7
o2
n19.8
o2
v6
v8
o2
n19.8
o2
v7
v9
o54
42
o2
n100
o5
o0
v1
o16
o5
v0
n2
n2
o2
n100
o5
o0
v2
o16
o5
v1
n2
n2
o2
n100
o5
o0
v3
o16
o5
v2
n2
n2
o2
n100
o5
o0
v4
o16
o5
v3
n2
n2
o2
n100
o5
o0
v5
o16
o5
v4
n2
n2
o2
n100
o5
o0
v6
o16
o5
v5
n2
n2
o2
n100
o5
o0
v7
o16
o5
v6
n2
n2
o5
o0
v0
n-1
n2
o5
o0
v1
n-1
n2
o5
o0
v2
n-1
n2
o5
o0
v3
n-1
n2
o5
o0
v4
n-1
n2
o5
o0
v5
n-1
n2
o5
o0
v6
n-1
n2
o2
n90
o5
o0
v3
o16
o5
v2
n2
n2
o2
n90
o5
o0
v4
o16
o5
v3
n2
n2
o2
n90
o5
o0
v5
o16
o5
v4
n2
n2
o2
n90
o5
o0
v6
o16
o5
v5
n2
n2
o2
n90
o5
o0
v7
o16
o5
v6
n2
n2
o2
n90
o5
o0
v8
o16
o5
v7
n2
n2
o2
n90
o5
o0
v9
o16
o5
v8
n2
n2
o5
o0
v2
n-1
n2
o5
o0
v3
n-1
n2
o5
o0
v4
n-1
n2
o5
o0
v5
n-1
n2
o5
o0
v6
n-1
n2
o5
o0
v7
n-1
n2
o5
o0
v8
n-1
n2
o2
n10.1
o5
o0
v1
n-1
n2
o2
n10.1
o5
o0
v2
n-1
n2
o2
n10.1
o5
o0
v3
n-1
n2
o2
n10.1
o5
o0
v4
n-1
n2
o2
n10.1
o5
o0
v5
n-1
n2
o2
n10.1
o5
o0
v6
n-1
n2
o2
n10.1
o5
o0
v7
n-1
n2
o2
n10.1
o5
o0
v3
n-1
n2
o2
n10.1
o5
o0
v4
n-1
n2
o2
n10.1
o5
o0
v5
n-1
n2
o2
n10.1
o5
o0
v6
n-1
n2
o2
n10.1
o5
o0
v7
n-1
n2
o2
n10.1
o5
o0
v8
n-1
n2
o2
n10.1
o5
o0
v9
n-1
n2
n19.8
x10
0 -2
1 -0.5
2 3
3 0.33333
4 -4
5 -0.25
6 5
7 0.2
8 -6
9 -0.16667
r
4 1
4 1
4 1
4 1
4 1
b
3
3
3
3
3
3
3
3
3
3
k9
5
10
14
18
21
24
26
28
29
J0 2
0 0
1 0
J1 4
0 0
1 0
2 0
3 0
J2 6
0 0
1 0
2 0
3 0
4 0
5 0
J3 8
0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
J4 10
0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
G0 10
0 0
1 -19.8
2 -19.8
3 -39.6
4 -39.6
5 -39.6
6 -39.6
7 -39.6
8 -19.8
9 -19.8
