g3 1 1 0 # unnamed problem generated by COEK
 2 3 1 0 0 0 # vars, constraints, objectives, ranges, eqns, lcons
 3 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 2 2 2 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 6 2 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o2
v0
v1
C1
o2
n-0.008
o5
v0
n2
C2
o5
o0
v1
n-50
n2
O0 0
o54
3
o2
n-0.030234
o2
v0
v1
o54
16
o2
n0.0020567
o5
v0
n3
o2
n-1.0345e-05
o5
v0
n4
o2
o2
n0.00128134
v1
o5
v0
n2
o2
o2
n2.266e-07
o5
v0
n4
v1
o2
n-0.25645
o5
v1
n2
o2
n0.0034604
o5
v1
n3
o2
n-1.3514e-05
o5
v1
n4
o3
n28.106
o0
v1
n1
o2
o2
n5.2375e-06
o5
v0
n2
o5
v1
n2
o2
o2
n6.3e-08
o5
v0
n3
o5
v1
n2
o2
o2
n7e-10
o5
v0
n3
o5
v1
n3
o2
o2
n0.0003405
v0
o5
v1
n2
o2
o2
n1.6638e-06
v0
o5
v1
n3
o2
n2.8673
o44
o2
o2
n0.0005
v0
v1
o2
o2
n3.5256e-05
o5
v0
n3
v1
o2
n-0.12694
o5
v0
n2
n-75.196
x2
0 90
1 10
r
2 700
2 0
2 -275
b
1 75
1 65
k1
3
J0 2
0 0
1 0
J1 2
0 0
1 1
J2 2
0 -5
1 0
G0 2
0 3.8112
1 6.8306
