g3 1 1 0 # unnamed problem generated by COEK
 10 8 1 0 0 0 # vars, constraints, objectives, ranges, eqns, lcons
 5 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 5 10 5 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 32 10 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
n0
C3
o54
3
o2
n-3
o5
o0
v0
n-2
n2
o2
n-4
o5
o0
v1
n-3
n2
o2
n-2
o5
v2
n2
C4
o0
o2
n-5
o5
v0
n2
o2
n-1
o5
o0
v2
n-6
n2
C5
o54
3
o2
n-0.5
o5
o0
v0
n-8
n2
o2
n-2
o5
o0
v1
n-4
n2
o2
n-3
o5
v4
n2
C6
o0
o2
n2
o2
v0
v1
o0
o2
n-1
o5
v0
n2
o2
n-2
o5
o0
v1
n-2
n2
C7
o2
n-12
o5
o0
v8
n-8
n2
O0 0
o54
3
o2
v0
v1
o54
10
o5
v0
n2
o5
v1
n2
o5
o0
v2
n-10
n2
o2
n4
o5
o0
v3
n-5
n2
o5
o0
v4
n-3
n2
o2
n2
o5
o0
v5
n-1
n2
o2
n5
o5
v6
n2
o2
n7
o5
o0
v7
n-11
n2
o2
n2
o5
o0
v8
n-10
n2
o5
o0
v9
n-7
n2
n45
x10
0 2
1 3
2 5
3 5
4 1
5 2
6 7
7 3
8 6
9 10
r
2 -105
2 0
2 -12
2 -120
2 -40
2 -30
2 0
2 0
b
3
3
3
3
3
3
3
3
3
3
k9
8
16
18
20
22
24
26
28
30
J0 4
0 -4
1 -5
6 3
7 -9
J1 4
0 -10
1 8
6 17
7 -2
J2 4
0 8
1 -2
8 -5
9 2
J3 4
0 0
1 0
2 0
3 7
J4 4
0 0
1 -8
2 0
3 2
J5 4
0 0
1 0
4 0
5 1
J6 4
0 0
1 0
4 -14
5 6
J7 4
0 3
1 -6
8 0
9 7
G0 10
0 -14
1 -16
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
