g3 1 1 0 # unnamed problem generated by COEK
 31 21 1 0 21 0 # vars, constraints, objectives, ranges, eqns, lcons
 21 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 7 1 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 70 1 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o2
n1250
o46
v0
C1
o2
n15625
o41
v0
C2
o2
n1250
o41
v0
C3
o2
n1250
o46
v4
C4
o2
n15625
o41
v4
C5
o2
n1250
o41
v4
C6
o2
n3750
o46
v8
C7
o2
n93750
o41
v8
C8
o2
n3750
o41
v8
C9
o2
n3750
o46
v12
C10
o2
n93750
o41
v12
C11
o2
n3750
o41
v12
C12
o2
n3750
o46
v16
C13
o2
n93750
o41
v16
C14
o2
n3750
o41
v16
C15
o2
n9000
o46
v20
C16
o2
n405000
o41
v20
C17
o2
n9000
o41
v20
C18
o2
n9000
o46
v24
C19
o2
n405000
o41
v24
C20
o2
n9000
o41
v24
O0 0
o2
n-1
o2
v28
v28
x7
0 0.5
4 0.5
8 0.5
12 0.5
16 0.5
20 0.5
24 0.5
r
4 0
4 10000
4 800
4 0
4 10000
4 800
4 0
4 40000
4 1600
4 0
4 40000
4 1600
4 0
4 40000
4 1600
4 0
4 129600
4 2880
4 0
4 100000
4 1000
b
0 0 1.58
4 0
4 0
4 0
0 0 1.58
3
3
3
0 0 1.58
3
3
3
0 0 1.58
3
3
3
0 0 1.58
3
3
3
0 0 1.58
3
3
3
0 0 1.58
3
3
3
3
3
3
k30
3
4
5
7
10
12
14
17
20
22
24
27
30
32
34
37
40
42
44
47
50
52
54
57
60
62
64
67
68
69
J0 3
0 0
1 1
5 -1
J1 4
0 0
2 1
3 25
6 -1
J2 3
0 0
3 1
7 -1
J3 3
4 0
5 1
9 -1
J4 4
4 0
6 1
7 25
10 -1
J5 3
4 0
7 1
11 -1
J6 3
8 0
9 1
13 -1
J7 4
8 0
10 1
11 50
14 -1
J8 3
8 0
11 1
15 -1
J9 3
12 0
13 1
17 -1
J10 4
12 0
14 1
15 50
18 -1
J11 3
12 0
15 1
19 -1
J12 3
16 0
17 1
21 -1
J13 4
16 0
18 1
19 50
22 -1
J14 3
16 0
19 1
23 -1
J15 3
20 0
21 1
25 -1
J16 4
20 0
22 1
23 90
26 -1
J17 3
20 0
23 1
27 -1
J18 3
24 0
25 1
28 -1
J19 4
24 0
26 1
27 90
29 -1
J20 3
24 0
27 1
30 -1
G0 1
28 0
