g3 1 1 0 # unnamed problem generated by COEK
 2 0 1 0 0 0 # vars, constraints, objectives, ranges, eqns, lcons
 0 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 0 2 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 0 2 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
O0 0
o54
10
o5
o0
n4
o16
o0
o44
v0
o44
v1
n2
o5
o0
n6
o16
o0
o44
o2
n2
v0
o44
o2
n2
v1
n2
o5
o0
n8
o16
o0
o44
o2
n3
v0
o44
o2
n3
v1
n2
o5
o0
n10
o16
o0
o44
o2
n4
v0
o44
o2
n4
v1
n2
o5
o0
n12
o16
o0
o44
o2
n5
v0
o44
o2
n5
v1
n2
o5
o0
n14
o16
o0
o44
o2
n6
v0
o44
o2
n6
v1
n2
o5
o0
n16
o16
o0
o44
o2
n7
v0
o44
o2
n7
v1
n2
o5
o0
n18
o16
o0
o44
o2
n8
v0
o44
o2
n8
v1
n2
o5
o0
n20
o16
o0
o44
o2
n9
v0
o44
o2
n9
v1
n2
o5
o0
n22
o16
o0
o44
o2
n10
v0
o44
o2
n10
v1
n2
x2
0 0.3
1 0.4
b
3
3
k1
0
G0 2
0 0
1 0
