g3 1 1 0 # unnamed problem generated by COEK
 8 3 1 0 3 0 # vars, constraints, objectives, ranges, eqns, lcons
 0 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 0 8 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 3 8 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
n0
O0 0
o54
5
o5
o54
9
o2
n-3.933
v0
o2
n0.107
v1
o2
n0.126
v2
n0
o2
n-9.99
v4
n0
o2
n-45.83
v6
o2
n-7.64
v7
o54
4
o2
o2
n-0.727
v1
v2
o2
o2
n8.390000000000001
v2
v3
o16
o2
o2
n684.4
v3
v4
o2
o2
n63.5
v3
v1
n2
o5
o54
9
n0
o2
n-0.987
v1
n0
o2
n-22.95
v3
n0
o2
n-28.37
v5
n0
n0
o0
o2
o2
n0.949
v0
v2
o2
o2
n0.173
v0
v4
n2
o5
o54
9
o2
n0.002
v0
n0
o2
n-0.235
v2
n0
o2
n5.67
v4
n0
o2
n-0.921
v6
o2
n-6.51
v7
o54
3
o2
o2
n-0.716
v0
v1
o16
o2
o2
n1.578
v0
v3
o2
o2
n1.132
v3
v1
n2
o5
o54
9
n0
v1
n0
o2
n-1
v3
n0
o2
n-0.168
v5
n0
n0
o2
o2
n-1
v0
v4
n2
o5
o54
9
n0
n0
o2
n-1
v2
n0
o2
n-0.196
v4
n0
o2
n-0.0071
v6
n0
o2
v0
v3
n2
x8
0 0
1 0
2 0
3 0
4 0
5 -0.05
6 0.1
7 0
r
4 -0.05
4 0.1
4 0
b
3
3
3
3
3
3
3
3
k7
0
0
0
0
0
1
2
J0 1
5 1
J1 1
6 1
J2 1
7 1
G0 8
0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
