g3 1 1 0 # unnamed problem generated by COEK
 5 2 1 0 2 0 # vars, constraints, objectives, ranges, eqns, lcons
 2 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 4 3 2 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 6 3 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o0
o2
n-1
o5
v3
n2
o5
v1
n2
C1
o54
3
o5
v0
n2
o5
v1
n2
o2
n-1
o5
v4
n2
O0 0
o54
3
o5
v0
n2
o5
v1
n2
o5
v2
n2
x5
0 1
1 1
2 1
3 0
4 0
r
4 1
4 1
b
3
3
3
3
3
k4
2
4
4
5
J0 3
0 1
1 0
3 0
J1 3
0 0
1 0
4 0
G0 3
0 0
1 0
2 0
