g3 1 1 0 # unnamed problem generated by COEK
 10 21 1 0 7 0 # vars, constraints, objectives, ranges, eqns, lcons
 4 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 7 2 1 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 35 6 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
C1
n0
C2
n0
C3
n0
C4
n0
C5
n0
C6
n0
C7
n0
C8
n0
C9
n0
C10
n0
C11
n0
C12
n0
C13
n0
C14
n0
C15
o3
o0
v1
v4
v0
C16
o2
o2
n0.01
v0
o54
3
n112
o2
n13.167
v7
o16
o2
n0.6667
o5
v7
n2
C17
o2
n0.038
o5
v7
n2
C18
n0
C19
n0
C20
o3
o2
n98000
v2
o0
o2
v3
v8
o2
n1000
v2
O0 0
o2
n-0.063
o2
v3
v6
x10
0 1745
1 12000
2 110
3 3048.289701727279
4 1973.913165464697
5 89.19832477429978
6 92.77060126854636
7 8.007973160724754
8 3.560779555148116
9 145.3118038056391
r
2 0
2 0
2 85
2 90
2 3
2 0.01
2 145
1 5000
1 2000
1 93
1 95
1 12
1 4
1 162
4 0
4 0
4 0
4 57.425
4 -133
4 35.82
4 0
b
0 1e-05 2000
0 1e-05 16000
0 1e-05 120
3
3
3
3
3
3
3
k9
3
4
5
10
14
18
22
27
31
J0 1
3 1
J1 1
4 1
J2 1
5 1
J3 1
6 1
J4 1
7 1
J5 1
8 1
J6 1
9 1
J7 1
3 1
J8 1
4 1
J9 1
5 1
J10 1
6 1
J11 1
7 1
J12 1
8 1
J13 1
9 1
J14 3
0 1
3 -1.22
4 1
J15 4
0 0
1 0
4 0
7 1
J16 3
0 0
3 1
7 0
J17 3
5 -0.325
6 1
7 -1.098
J18 2
6 -3
9 1
J19 2
8 1
9 0.222
J20 4
2 0
3 0
5 1
8 0
G0 6
0 5.04
1 0.035
2 10
3 0
4 3.36
6 0
