g3 1 1 0 # unnamed problem generated by COEK
 5 3 1 3 0 0 # vars, constraints, objectives, ranges, eqns, lcons
 3 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 5 3 3 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 13 3 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
o54
3
o2
n0.0006262
o2
v0
v3
o2
n0.0056858
o2
v1
v4
o2
n-0.0022053
o2
v2
v4
C1
o54
3
o2
n0.0029955
o2
v0
v1
o2
n0.0071317
o2
v1
v4
o2
n0.0021813
o5
v2
n2
C2
o54
3
o2
n0.0012547
o2
v0
v2
o2
n0.0019085
o2
v2
v3
o2
n0.0047026
o2
v2
v4
O0 0
o54
3
o2
n0.8356891
o2
v0
v4
o2
n5.3578547
o5
v2
n2
n-40792.141
x5
0 78
1 33
2 27
3 27
4 27
r
0 -85.334407 6.665593000000001
0 9.48751 29.48751
0 10.699039 15.699039
b
0 78 102
0 33 45
0 27 45
0 27 45
0 27 45
k4
3
5
8
10
J0 5
0 0
1 0
2 0
3 0
4 0
J1 4
0 0
1 0
2 0
4 0
J2 4
0 0
2 0
3 0
4 0
G0 3
0 37.293239
2 0
4 0
