g3 1 1 0 # unnamed problem generated by COEK
 2 1 1 0 1 0 # vars, constraints, objectives, ranges, eqns, lcons
 0 1 # nonlinear constraints, objectives
 0 0 # network constraints: nonlinear, linear
 0 2 0 # nonlinear vars in constraints, objectives, both
 0 0 0 1 # linear network variables; functions; arith, flags
 0 0 0 0 0 # discrete variables: binary, integer, nonlinear (b,c,o)
 2 2 # nonzeros in Jacobian, gradients
 0 0 # max name lengths: constraints, variables
 0 0 0 0 0 # common exprs: b,c,o,c1,o1
C0
n0
O0 0
o5
o0
v0
o2
n-1
v1
n2
r
4 1
b
2 0
2 0
k1
1
J0 2
0 1
1 1
G0 2
0 0
1 0
