#!/usr/bin/env python
#
# pygurobi_solve0 [-d] <solver> <model> [<data> ...]
#

import sys
import os.path

sys.path.insert(1, os.path.dirname(os.path.abspath(__file__)) )
from models import create_instance, print_help

if len(sys.argv) == 1:
    print("pygurobi_solve0 [-d] <solver> <model> [<data> ...]")
    print_help()
    sys.exit(1)

i=1
if sys.argv[i] == '-d':
    debug=True
    i += 1
else:
    debug=False
solver = sys.argv[i]        # INGORED - only can run gurobi's solvers
i += 1
model = sys.argv[i]
i += 1
data = [int(val) for val in sys.argv[i:]]

instance = create_instance(model, data)
if instance is None:
    print("Unknown pygurobi model '%s'" % model)
    sys.exit(1)

instance.Params.OutputFlag = debug
instance.Params.TimeLimit = 0
instance.optimize()
