INCLUDE(FindPackageHandleStandardArgs)

FIND_PROGRAM(GCOVR_EXECUTABLE gcovr 
  HINTS ${GCOVR_ROOT}
        ${GCOVR_ROOT}/bin
        ENV ${PATH})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(gcovr DEFAULT_MSG GCOVR_EXECUTABLE)

MARK_AS_ADVANCED(GCOVR_EXECUTABLE)
